### ISSUE TITLE
Upload avatar / Submit

### ISSUE THREAD

**Issue by iiCe89** [iiCe89/Lynk_Social#23]
Upload avatar / Submit is broken when uploading new avatar and submitting on profile.blade.php view the action reverts back to home page and causes error on Feed.blade.php
<img width="1218" alt="Screenshot 2019-10-11 at 15 58 20" src="https://user-images.githubusercontent.com/19858208/66662029-f7714080-ec3f-11e9-8d85-89e412126138.png">

**Comment by stevepop** [comment]
I will look into this issue

**Comment by stevepop** [comment]
This has now been fixed in PR #26

**Comment by stevepop** [comment]
PR merged. Closing this issue.
