### ISSUE TITLE
feat -Create post

### ISSUE THREAD

**Issue by iiCe89** [iiCe89/Lynk_Social#4]
Create post that displays on feed.blade.php view. User should also be able to add emoji's & image/gif

**Comment by iiCe89** [comment]
https://www.figma.com/file/XUFyrd8LdMqVxSHvAfPVDn/Lynk_social?node-id=0%3A1

**Comment by stevepop** [comment]
This is now done in PR #30 
The database migration for Posts has been changed. Please run `php artisan migrate:refresh' to reflect the changes.

**Comment by iiCe89** [comment]
this is now complete & working
